### ISSUE TITLE
Failed to Create On-rep-seq virtual environment

### ISSUE THREAD

**Issue by AlexGaithuma** [lauramilena3/On-rep-seq#2]
When I run the command: conda env create -n On-rep-seq -f On-rep-seq.yaml
I get the following....

Fetching package metadata ...................
Solving package specifications: 

NoPackagesFoundError: Dependencies missing in current linux-64 channels: 
  - kraken2 2.0.7* -> libgcc-ng >=7.3.0
  - kraken2 2.0.7* -> libstdcxx-ng >=7.3.0
  - kraken2 2.0.7* -> perl >=5.26.2,<5.26.3.0a0
  - matplotlib 3.0.3* -> matplotlib-base 3.0.3 py37h5f35d83_1 -> freetype >=2.9.1,<3.0a0 -> libgcc-ng >=4.9
  - matplotlib 3.0.3* -> matplotlib-base 3.0.3 py37h5f35d83_1 -> libstdcxx-ng >=7.3.0
  - matplotlib 3.0.3* -> matplotlib-base 3.0.3 py37h5f35d83_1 -> python >=3.7,<3.8.0a0 -> openssl >=1.0.2p,<1.0.3a
  - matplotlib 3.0.3* -> matplotlib-base 3.0.3 py37h5f35d83_1 -> python >=3.7,<3.8.0a0 -> sqlite >=3.25.3,<4.0a0
  - matplotlib 3.0.3* -> matplotlib-base 3.0.3 py37h5f35d83_1 -> python >=3.7,<3.8.0a0 -> xz >=5.2.4,<5.3.0a0

Kindly assist.

**Comment by lauramilena3** [comment]
Can you please check your conda version with:
conda --version
The version should be >=4.6
If not, try updating it with:
conda update conda

**Comment by AlexGaithuma** [comment]
Thanks. The command: conda --version
gives: conda 4.3.16

I ran the command: conda update conda
then 
conda --version still gives me: conda 4.3.16

I even tried 
conda install -c conda-forge conda
and
conda install -c anaconda conda 
The NoPackagesFoundError still persists..

conda --version still gives me: conda 4.3.16

**Comment by AlexGaithuma** [comment]
Thanks lauramilena3 

I finally solved it. I uninstalled Anaconda2 and installed Anaconda3
conda --version: 4.7

Creating the environment worked!

**Comment by lauramilena3** [comment]
Great! I made some edits on the repo this morning to add a newer version of Snakemake. Please update the repository with "git pull"
Then, create the environment as you did before.  (conda env create -n On-rep-seq -f On-rep-seq.yaml)
