### ISSUE TITLE
Failed with several errors

### ISSUE THREAD

**Issue by AlexGaithuma** [lauramilena3/On-rep-seq#3]
## I downloaded the SRA from your paper and run the On-rep-seq but it failed...What could be the cause?

fastqDir="/media/bioadmin/24e12c01-7941-49f5-9647-eeebabd15082/DATA/ncbi/public/sra"
reusultDir="/media/bioadmin/2E1EA9711EA9332F/Analysis/ON-rep-seq"
nCores="6"
cd '/media/bioadmin/2E1EA9711EA9332F/On-rep-seq'
(On-rep-seq) bioadmin@bioadmin-B75M-D3V-JP[On-rep-seq] snakemake -j $nCores --use-conda --config basecalled_dir=$fastqDir results_dir=$reusultDir

## The ouput:
> Building DAG of jobs...
Creating conda environment rules/envs/R.yaml...
Downloading and installing remote packages.
Environment for rules/envs/R.yaml created (location: .snakemake/conda/d88797b6)
Creating conda environment rules/envs/canu.yaml...
Downloading and installing remote packages.
Environment for rules/envs/canu.yaml created (location: .snakemake/conda/c016cea8)
Creating conda environment rules/envs/On-rep-seq.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/rules/envs/On-rep-seq.yaml:
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Pip subprocess error:
  Running command git clone -q https://github.com/lauramilena3/Porechop /tmp/pip-req-build-fid8p3wn
  ERROR: Command errored out with exit status 1:
   command: /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fid8p3wn/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fid8p3wn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-cb5baidq --python-tag cp37
       cwd: /tmp/pip-req-build-fid8p3wn/
  Complete output (48 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/porechop
  copying porechop/porechop.py -> build/lib/porechop
  copying porechop/nanopore_read.py -> build/lib/porechop
  copying porechop/adapters.py -> build/lib/porechop
  copying porechop/__init__.py -> build/lib/porechop
  copying porechop/adapters_orig_v0.2.2.py -> build/lib/porechop
  copying porechop/version.py -> build/lib/porechop
  copying porechop/cpp_function_wrappers.py -> build/lib/porechop
  copying porechop/misc.py -> build/lib/porechop
  Cleaning previous compilation: make clean
  rm -f porechop/src/adapter_align.o porechop/src/alignment.o
  Compiling Porechop: make -j 8
  g++ -std=c++14 -Iporechop/include -fPIC -O3 -D NDEBUG -Wall -Wextra -pedantic -mtune=native -c -o porechop/src/adapter_align.o porechop/src/adapter_align.cpp
  g++: error: unrecognized command line option ‘-std=c++14’
  make: *** [porechop/src/adapter_align.o] Error 1
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/porechop
  copying build/lib/porechop/porechop.py -> build/bdist.linux-x86_64/wheel/porechop
  copying build/lib/porechop/nanopore_read.py -> build/bdist.linux-x86_64/wheel/porechop
  copying build/lib/porechop/adapters.py -> build/bdist.linux-x86_64/wheel/porechop
  copying build/lib/porechop/__init__.py -> build/bdist.linux-x86_64/wheel/porechop
  copying build/lib/porechop/adapters_orig_v0.2.2.py -> build/bdist.linux-x86_64/wheel/porechop
  copying build/lib/porechop/version.py -> build/bdist.linux-x86_64/wheel/porechop
  copying build/lib/porechop/cpp_function_wrappers.py -> build/bdist.linux-x86_64/wheel/porechop
  copying build/lib/porechop/misc.py -> build/bdist.linux-x86_64/wheel/porechop
  running install_egg_info
  running egg_info
  creating porechop.egg-info
  writing porechop.egg-info/PKG-INFO
  writing dependency_links to porechop.egg-info/dependency_links.txt
  writing entry points to porechop.egg-info/entry_points.txt
  writing top-level names to porechop.egg-info/top_level.txt
  writing manifest file 'porechop.egg-info/SOURCES.txt'
  reading manifest file 'porechop.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'porechop.egg-info/SOURCES.txt'
  Copying porechop.egg-info to build/bdist.linux-x86_64/wheel/porechop-0.2.3-py3.7.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'porechop/cpp_functions.so'
  ----------------------------------------
 > ERROR: Failed building wheel for porechop
  ERROR: Command errored out with exit status 1:
   command: /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fid8p3wn/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fid8p3wn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-req-build-fid8p3wn
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
 > error: option --all not recognized
  ----------------------------------------
 > ERROR: Failed cleaning build dir for porechop
    ERROR: Command errored out with exit status 1:
     command: /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fid8p3wn/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fid8p3wn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s2_lr9yn/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-req-build-fid8p3wn/
    Complete output (41 lines):
    running install
    running build
    running build_py
    Cleaning previous compilation: make clean
    rm -f porechop/src/adapter_align.o porechop/src/alignment.o
    Compiling Porechop: make -j 8
    g++ -std=c++14 -Iporechop/include -fPIC -O3 -D NDEBUG -Wall -Wextra -pedantic -mtune=native -c -o porechop/src/adapter_align.o porechop/src/adapter_align.cpp
    g++: error: unrecognized command line option ‘-std=c++14’
    make: *** [porechop/src/adapter_align.o] Error 1
    running install_lib
    creating /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop
    copying build/lib/porechop/porechop.py -> /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop
    copying build/lib/porechop/nanopore_read.py -> /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop
    copying build/lib/porechop/adapters.py -> /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop
    copying build/lib/porechop/__init__.py -> /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop
    copying build/lib/porechop/adapters_orig_v0.2.2.py -> /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop
    copying build/lib/porechop/version.py -> /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop
    copying build/lib/porechop/cpp_function_wrappers.py -> /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop
    copying build/lib/porechop/misc.py -> /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop
    byte-compiling /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop/porechop.py to porechop.cpython-37.pyc
    byte-compiling /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop/nanopore_read.py to nanopore_read.cpython-37.pyc
    byte-compiling /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop/adapters.py to adapters.cpython-37.pyc
    byte-compiling /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop/__init__.py to __init__.cpython-37.pyc
    byte-compiling /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop/adapters_orig_v0.2.2.py to adapters_orig_v0.2.2.cpython-37.pyc
    byte-compiling /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop/version.py to version.cpython-37.pyc
    byte-compiling /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop/cpp_function_wrappers.py to cpp_function_wrappers.cpython-37.pyc
    byte-compiling /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop/misc.py to misc.cpython-37.pyc
    running install_egg_info
    running egg_info
    writing porechop.egg-info/PKG-INFO
    writing dependency_links to porechop.egg-info/dependency_links.txt
    writing entry points to porechop.egg-info/entry_points.txt
    writing top-level names to porechop.egg-info/top_level.txt
    reading manifest file 'porechop.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'porechop.egg-info/SOURCES.txt'
    Copying porechop.egg-info to /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/lib/python3.7/site-packages/porechop-0.2.3-py3.7.egg-info
    running install_scripts
    Installing porechop script to /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/bin
    writing list of installed files to '/tmp/pip-record-s2_lr9yn/install-record.txt'
    error: [Errno 2] No such file or directory: 'porechop/cpp_functions.so'
    ----------------------------------------
> ERROR: Command errored out with exit status 1: /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fid8p3wn/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fid8p3wn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s2_lr9yn/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

> CondaEnvException: Pip failed

> Ran pip subprocess with arguments:
['/media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/ce54c2c7/bin/python', '-m', 'pip', 'install', '-U', '-r', '/media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/condaenv.2b27p22o.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/lauramilena3/Porechop (from -r /media/bioadmin/2E1EA9711EA9332F/On-rep-seq/.snakemake/conda/condaenv.2b27p22o.requirements.txt (line 1))
  Cloning https://github.com/lauramilena3/Porechop to /tmp/pip-req-build-fid8p3wn
Building wheels for collected packages: porechop
  Building wheel for porechop (setup.py): started
  Building wheel for porechop (setup.py): finished with status 'error'
  Running setup.py clean for porechop
Failed to build porechop
Installing collected packages: porechop
    Running setup.py install for porechop: started
    Running setup.py install for porechop: finished with status 'error'

**Comment by lauramilena3** [comment]
Thanks for the output Alex. I suspect you are using an older version of gcc. For installing porechop you need v4.9.1 or later. You can try using this command after activating the On-rep-seq environment:
conda install -c conda-forge libgcc

**Comment by AlexGaithuma** [comment]
Thanks.
Upgrading gcc worked.
