### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by AlexGaithuma** [lauramilena3/On-rep-seq#4]
## Thanks lauramilena3 for your open access pipeline.

I would like to use ON-rep-seq very soon in an extensive ecological study. I need to run the pipeline and see the output so that I can customize it to my study and analysis.

Could you provide some test data (fastq)

**Comment by lauramilena3** [comment]
Hi Alex,
Please update the repository to the last version. Enter the On-rep-seq folder and pull the updated repo with:
git pull
Regarding your questions:
1. Could you please send me the error message? The pipeline should work for that dataset.
2. The adapters used for demultiplexing are handled by porechop. Hence, you have to manually modify the file named adapters.py in the porechop installation. Try to look for the file with:
find . -name "adapters.py"
Open that file and look for a section that describes "INSTRUCTIONS FOR ADDING CUSTOM ADAPTERS".

**Comment by AlexGaithuma** [comment]
Thanks for your support lauramilena3 
Runs after git pull
(The SRA data is already demultiplexed) --didnt pay close attention.

Thanks a alot
