### ISSUE TITLE
kraken2-build error

### ISSUE THREAD

**Issue by AlexGaithuma** [lauramilena3/On-rep-seq#5]
kraken2-build --download-taxonomy --db db/NCBI-bacteria --threads $nCores
Downloading nucleotide est accession to taxon map...rsync: link_stat "/taxonomy/accession2taxid/nucl_est.accession2taxid.gz" (in pub) failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1659) [Receiver=3.1.3]

Apparently its an NCBI repository change issue
https://github.com/DerrickWood/kraken2/issues/101

**Comment by lauramilena3** [comment]
Thank you for pointing that out. Please activate On-rep-seq's conda environment and install the missing library "libiconv". That should fix the bug. I will fix the code so it won't happen again.

source activate On-rep-seq
conda install -c conda-forge libiconv
