### ISSUE TITLE
Error in rule LCPsCluster

### ISSUE THREAD

**Issue by AlexGaithuma** [lauramilena3/On-rep-seq#6]
I ran into an error

    Error in rule LCPsCluster:
    jobid: 2
    output: /home/alex/On-rep-seq/02_LCPs/LCP_clustering_heatmaps.ipynb, /home/alex/On-rep-seq/02_LCPs/LCP_clustering_heatmaps.html, /home/alex/On-rep-seq/02_LCPs/LCP_clustering_heatmap_large.png, /home/alex/On-rep-seq/02_LCPs/LCP_clustering_heatmap.png, /home/alex/On-rep-seq/02_LCPs/LCP_clustering_flowgrams_clustering_order.pdf, /home/alex/On-rep-seq/02_LCPs/LCPsClusteringData, /home/alex/On-rep-seq/02_LCPs/r_saved_images
    conda-env: /home/alex/tools/On-rep-seq/.snakemake/conda/6c9e51be
    shell:
        
		mkdir -p "/home/alex/On-rep-seq/02_LCPs/LCPsClusteringData"
		cp "/home/alex/On-rep-seq/02_LCPs"/*.txt "/home/alex/On-rep-seq/02_LCPs/LCPsClusteringData"
		find "/home/alex/On-rep-seq/02_LCPs/LCPsClusteringData" -size -100c -delete
		Rscript -e "IRkernel::installspec()"
        CLUSTSCRIPT="$(realpath ./scripts/LCpCluster.R)"
        ( cd "/home/alex/On-rep-seq/02_LCPs"; "$CLUSTSCRIPT" LCPsClusteringData/ "runnable_jupyter_on-rep-seq_flowgrams_clustering_heatmaps.ipynb" )
		mv "/home/alex/On-rep-seq/02_LCPs/runnable_jupyter_on-rep-seq_flowgrams_clustering_heatmaps.ipynb" "/home/alex/On-rep-seq/02_LCPs/LCP_clustering_heatmaps.ipynb"
		mv "/home/alex/On-rep-seq/02_LCPs/runnable_jupyter_on-rep-seq_flowgrams_clustering_heatmaps_clustering_heatmap_01.png" "/home/alex/On-rep-seq/02_LCPs/LCP_clustering_heatmap_large.png"
		mv "/home/alex/On-rep-seq/02_LCPs/runnable_jupyter_on-rep-seq_flowgrams_clustering_heatmaps_clustering_heatmap_02.png" "/home/alex/On-rep-seq/02_LCPs/LCP_clustering_heatmap.png"
		mv "/home/alex/On-rep-seq/02_LCPs/runnable_jupyter_on-rep-seq_flowgrams_clustering_heatmaps_flowgrams_clustering_order.pdf" "/home/alex/On-rep-seq/02_LCPs/LCP_clustering_flowgrams_clustering_order.pdf"
		jupyter-nbconvert --to html --template full "/home/alex/On-rep-seq/02_LCPs/LCP_clustering_heatmaps.ipynb" 
		
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

    Removing output files of failed job LCPsCluster since they might be corrupted:
    /home/alex/On-rep-seq/02_LCPs/LCPsClusteringData
    Shutting down, this might take some time.
    Exiting because a job execution failed. Look above for error message
    Complete log: /home/alex/tools/On-rep-seq/.snakemake/log/2019-12- 
    05T163606.475904.snakemake.log

I ran the commands in (one of the commands exited with non-zero exit code) and I got:

    (on-rep-seq) [alex@ororon ~]$  CLUSTSCRIPT="$(realpath ./scripts/LCpCluster.R)"-bash: realpath: 
    command not found

I am running the pipeline on RedHat server and without admin rights I cannot install the coreutils package that contains realpath. The server has readlink instead.

**Comment by AlexGaithuma** [comment]
I think I found the problem.

I ran the commands in (one of the comreadlinkmands exited with non-zero exit code) and I got:

    (on-rep-seq) [alex@ororon ~]$  CLUSTSCRIPT="$(realpath ./scripts/LCpCluster.R)"-bash: realpath: 
    command not found

I am running the pipeline on RedHat server and without admin rights I cannot install the coreutils package that contains realpath. The server has readlink instead.

How do I proceed? any suggestions?

**Comment by lauramilena3** [comment]
Hi Alex, I added coreutils to the conda environment used by "rule LCPsCluster".  Please pull the repository and run On-rep-seq again. It should fix your problem.

**Comment by AlexGaithuma** [comment]
Thanks!
Still getting an error from the command: Rscript -e "IRkernel::installspec()"
The output is as follows:

    Error in IRkernel::installspec() : 
    jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
    In addition: Warning message:
    In system2("jupyter", c("kernelspec", "--version"), FALSE, FALSE) :
    error in running command
    Execution halted

**Comment by lauramilena3** [comment]
Hello Alex, are you still having issues with the IRkernel?

**Comment by AlexGaithuma** [comment]
Thanks for your support.

I finally got it to work by adding some dependencies on the R.yaml file. 
This was the error....

    Error in IRkernel::installspec() : jupyter-client has to be installed but “jupyter kernelspec --version” 
    exited with code 127. In addition: Warning message: In system2("jupyter", c("kernelspec", "--version"), FALSE, FALSE) : error in running command Execution halted

However, I am no expert in this and I think some dependencies I added may not be needed.
This is how my R.yaml file looks like.

    channels:
      - au-eoed
      - conda-forge
      - bioconda
    dependencies:
      - gnu-parallel =20161122
      - jupyterlab =1.2.4
      - jupyter_core =4.6.1
      - jupyter_client =5.3.3
      - r-optparse =1.6.4
      - r-ggplot2 =3.1.0
      - r-signal =0.7
      - r-irkernel =1.1
      - r-gplots =3.0.1
      - r-cluster =2.0.7
      - r-heatmap3 =1.1.1
      - r-hash =2.2.6
      - r-fastmatch =1.1
      - r-latticeExtra =0.6
      - r-reshape =0.8.8
      - r-plotrix =3.7
      - r-matrixStats =0.54.0
      - r-gdata =2.18.0
      - perl =5.26.2
      - coreutils =8.25

I also had a previous problem with taxonomy assignments I don't know why but the
kraken2 =2.0.8_beta did not work for me so I used kraken2 =2.0.7 instead.
